SELECT
    A.PRODUCT_CODE,
    SUM(B.SALES_AMOUNT) * PRICE
FROM PRODUCT A
JOIN OFFLINE_SALE B ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.PRODUCT_CODE
ORDER BY
    SUM(B.SALES_AMOUNT) * PRICE DESC,
    A.PRODUCT_CODE ASC;