SELECT
    SUM(C.SCORE) AS SCORE,
    B.EMP_NO,
    B.EMP_NAME,
    B.POSITION,
    B.EMAIL
FROM HR_EMPLOYEES B
JOIN HR_GRADE C ON B.EMP_NO = C.EMP_NO
WHERE C.YEAR = '2022'
GROUP BY B.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;